// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFlbXniXUnXVw_bdN1XzPRd5WCHEUC4Ug',
    appId: '1:60669305899:web:1fd89d232cf1549057366e',
    messagingSenderId: '60669305899',
    projectId: 'sound-space-58e51',
    authDomain: 'sound-space-58e51.firebaseapp.com',
    storageBucket: 'sound-space-58e51.appspot.com',
    measurementId: 'G-D0VB3J3Y2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NXE6FB1HmMu4P5d4C9mcsbPz53S1SeM',
    appId: '1:60669305899:android:5a36be0aa38659c957366e',
    messagingSenderId: '60669305899',
    projectId: 'sound-space-58e51',
    storageBucket: 'sound-space-58e51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxdX3eerYmDrINpLk_Z22oCQdCK_85-A',
    appId: '1:60669305899:ios:0bf46be4cc79108657366e',
    messagingSenderId: '60669305899',
    projectId: 'sound-space-58e51',
    storageBucket: 'sound-space-58e51.appspot.com',
    iosClientId: '60669305899-rquu7mph3vguli0nm801uqlaaamrt30j.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
