name: build container

on: [ push ]

env:
  API_IMG: "ghcr.io/git-compendium/ci-docker/api:latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build .