name: flutter build

on: [ push ]

jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deps
        run: apt-get update && apt-get install -y curl git wget unzip python3
        run: git clone https://github.com/flutter/flutter.git /usr/local/flutter
        run: PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"
        run: flutter channel master
        run: flutter upgrade
        run: flutter config --enable-web
      - name: Build
        run: flutter build web
